# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish" # UNCOMMENT THIS LINE
baseURL = 'https://0andwild.com/'
defaultContentLanguage = "ko"
canonifyURLs = true
# title = '0AW Tech Blog'

[languages]
  [languages.ko]
  [languages.en]

[params.author]
name = "0AndWild"
image = "img/profile1.jpg"
imageQuality = 96
headline = "Deep Dive into Backend"
bio = "Always curious, always exploring new tech"
links = [
  { github = "https://github.com/0AndWild" },
  { linkedin = "https://linkedin.com/in/건영-박-158861275" },
  { email = "parkky3563@gmail.com" }
]

pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true

[pagination]
  pagerSize = 12

[imaging]
  anchor = 'Center'

[taxonomies]
  # post = "posts"
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[services]
  [services.googleAnalytics]
    ID = "G-QL6FY3F6WJ"

[related]
  threshold = 0
  toLower = true

    [[related.indices]]
        name = "tags"
        weight = 60

    [[related.indices]]
        name = "categories"
        weight = 70

    [[related.indices]]
        name = "series"
        weight = 90

    [[related.indices]]
        name = "authors"
        weight = 20
