disabled = false
languageCode = "ko-KR"
languageName = "í•œêµ­ì–´"
weight = 1
title = '0AndWild_log'

[params]
  displayName = "ğŸ‡°ğŸ‡· KO"
  isoCode = "ko-KR"
  logo = "img/logo.svg"
  rtl = false
  dateFormat = "2025-10-12"

[params.author]
  name = "ë°•ê±´ì˜"